### PR TITLE
Create User and Food Models #3: Done!~

### PR DESCRIPTION
**Pull request by MasterOfAlune**

### CODE REVIEW

**Review by Noorin99 — CHANGES_REQUESTED** [review]
Good job, Ammar. But, I think we need to improve some important things before merging. 
Below, I will list the requested changes: 

1- Install Prettier in VS Code and format the code. Be sure to format your code always before pushing it.
2- Make your research about categories and allergies and add them.
3- Remove unnecessary comments: we should have a clean code 
4- Update schema for date tracking ( date-created, date-modified). There is a way in Mongoose that handles date-created. 
5- Add the following fields to the address section: street name, street number, flat number, and district.
6- Implement phone number validation specifically for Turkish phone numbers.

**Review by fatimaali200 — CHANGES_REQUESTED** [review]
- I think u should add enum:[admin,cooker,customer] for role attribute.
- It will be good if u add a virtual field for fullname.
- Can u please update cook to be chief.

**Review by MOHAMMAD-ALMOHAMMAD — CHANGES_REQUESTED** [review]
The password field in the User document should be made optional not required, because some users will sign in with google/facebook

**Comment by MasterOfAlune** [comment]
> Good job, Ammar. But, I think we need to improve some important things before merging. Below, I will list the requested changes:
> 
> 1- Install Prettier in VS Code and format the code. Be sure to format your code always before pushing it. 2- Make your research about categories and allergies and add them. 3- Remove unnecessary comments: we should have a clean code 4- Update schema for date tracking ( date-created, date-modified). There is a way in Mongoose that handles date-created. 5- Add the following fields to the address section: street name, street number, flat number, and district. 6- Implement phone number validation specifically for Turkish phone numbers.

Done!~

**Comment by MasterOfAlune** [comment]
> * I think u should add enum:[admin,cooker,customer] for role attribute.
> * It will be good if u add a virtual field for fullname.
> * Can u please update cook to be chief.
> * Can u please update provider_id to be like provider_id :{ type:string,unique: true}

Done!~

**Comment by MasterOfAlune** [comment]
> The password field in the User document should be made optional not required, because some users will sign in with google/facebook

Won't be implemented as we mention before!~

**Comment by MasterOfAlune** [comment]
Please guys review the code again and comment if there any problems!

**Review by Noorin99 — APPROVED** [review]

**Review by fatimaali200 — APPROVED** [review]

**Pull request merged**
